name: Build and Deploy

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: true
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Create dist directory
      run: mkdir -p dist
      
    - name: Build Production Version
      run: |
        NODE_ENV=production npm run build-optimized
        ls -la dist/
      env:
        NODE_ENV: production
      
    - name: Verify build artifacts
      run: |
        echo "Checking for build artifacts..."
        if [ -f "dist/main.user.js" ]; then
          echo "✅ dist/main.user.js found!"
        elif [ -f "dist/dev.user.js" ]; then
          echo "⚠️ Found dev.user.js instead of main.user.js - renaming..."
          cp dist/dev.user.js dist/main.user.js
        else
          echo "🔍 Searching for user.js files..."
          find . -name "*.user.js" -type f
          echo "❌ Required build artifacts not found!"
          exit 1
        fi
      
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        
        # Create a temporary branch or use an existing one
        if git show-ref --quiet refs/remotes/origin/gh-pages; then
          git checkout -b gh-pages-temp origin/gh-pages
        else
          git checkout --orphan gh-pages-temp
        fi
        
        # Clean previous content
        git rm -rf . --quiet || true
        
        # Ensure we have the built file
        if [ ! -f "dist/main.user.js" ]; then
          echo "Error: dist/main.user.js not found after build!"
          find . -name "*.user.js" -type f
          exit 1
        fi
        
        # Copy the generated file
        echo "Copying main.user.js to root"
        cp dist/main.user.js ./main.user.js
        
        # Verify the file was copied correctly
        if [ ! -f "./main.user.js" ]; then
          echo "Error: Failed to copy main.user.js to root!"
          exit 1
        fi
        
        # Add and commit
        git add main.user.js
        git commit -m "Automated update $(date)"
        
        # Publish
        git push -f origin gh-pages-temp:gh-pages
        
        # Return to the original branch
        git checkout -