name: Build and Deploy

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: true
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Build Production Version
      run: npm run build
      
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        
        # Create a temporary branch or use an existing one
        if git show-ref --quiet refs/remotes/origin/gh-pages; then
          git checkout -b gh-pages-temp origin/gh-pages
        else
          git checkout --orphan gh-pages-temp
        fi
        
        # Clean previous content
        git rm -rf . --quiet || true
        
        # Copy the generated file
        mkdir -p dist
        cp dist/main.user.js main.user.js
        
        # Add and commit
        git add main.user.js
        git commit -m "Automated update $(date)"
        
        # Publish
        git push -f origin gh-pages-temp:gh-pages
        
        # Return to the original branch
        git checkout -